-- Создание таблицы для галереи
CREATE TABLE IF NOT EXISTS gallery (
    id INT PRIMARY KEY AUTO_INCREMENT,
    url VARCHAR(500) NOT NULL,
    alt_ru VARCHAR(255),
    alt_en VARCHAR(255),
    alt_uz VARCHAR(255),
    row_num INT NOT NULL DEFAULT 1,
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_row_position (row_num, position)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Создание таблицы для проектов
CREATE TABLE IF NOT EXISTS projects (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title_en VARCHAR(255) NOT NULL,
    title_ru VARCHAR(255) NOT NULL,
    title_uz VARCHAR(255) NOT NULL,
    description_en TEXT,
    description_ru TEXT,
    description_uz TEXT,
    image VARCHAR(500),
    category_en VARCHAR(100),
    category_ru VARCHAR(100),
    category_uz VARCHAR(100),
    status VARCHAR(50) DEFAULT 'Planning',
    duration VARCHAR(100),
    team TEXT,
    overview_en TEXT,
    overview_ru TEXT,
    overview_uz TEXT,
    objectives_en JSON,
    objectives_ru JSON,
    objectives_uz JSON,
    technologies_en JSON,
    technologies_ru JSON,
    technologies_uz JSON,
    impact_en TEXT,
    impact_ru TEXT,
    impact_uz TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status (status),
    INDEX idx_category (category_en)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Создание таблицы для членов команды
CREATE TABLE IF NOT EXISTS team_members (
    id VARCHAR(50) PRIMARY KEY,
    image VARCHAR(500),
    email VARCHAR(255),
    phone VARCHAR(50),
    name_ru VARCHAR(255) NOT NULL,
    name_en VARCHAR(255) NOT NULL,
    name_uz VARCHAR(255) NOT NULL,
    role_ru VARCHAR(255),
    role_en VARCHAR(255),
    role_uz VARCHAR(255),
    bio_ru TEXT,
    bio_en TEXT,
    bio_uz TEXT,
    biography_ru TEXT,
    biography_en TEXT,
    biography_uz TEXT,
    expertise_ru JSON,
    expertise_en JSON,
    expertise_uz JSON,
    education_ru JSON,
    education_en JSON,
    education_uz JSON,
    experience_ru JSON,
    experience_en JSON,
    experience_uz JSON,
    publications_ru JSON,
    publications_en JSON,
    publications_uz JSON,
    achievements_ru JSON,
    achievements_en JSON,
    achievements_uz JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
